--[[
  REAPER Companion - 自动启动管理模块
  职责：管理 REAPER 启动时自动运行脚本
--]]

local AutoStart = {}
local r = reaper

-- 获取启动脚本路径
-- @return string 启动脚本的完整路径，如果无法获取则返回 nil
local function get_startup_script_path()
  local resource_path = r.GetResourcePath()
  if not resource_path then
    return nil
  end
  
  -- REAPER 的启动脚本目录：Scripts/startup/
  local startup_dir = resource_path .. "/Scripts/startup"
  local startup_script = startup_dir .. "/zyc_ReaPet_auto_start.lua"
  
  return startup_script, startup_dir
end

-- 获取主脚本路径（当前运行的脚本）
-- @return string 主脚本的完整路径
local function get_main_script_path()
  -- 获取当前脚本的路径
  local script_path = debug.getinfo(1, "S").source:match("@(.*[\\//])")
  if not script_path then
    return nil
  end
  
  -- 查找主脚本文件（zyc_ReaPet.lua）
  -- 需要向上查找，因为可能在不同的子目录中
  local possible_paths = {
    script_path .. "zyc_ReaPet.lua",
    script_path .. "../zyc_ReaPet.lua",
    script_path .. "../../zyc_ReaPet.lua",
  }
  
  for _, path in ipairs(possible_paths) do
    -- 规范化路径
    path = path:gsub("/+", "/")
    path = path:gsub("\\+", "\\")
    
    local file = io.open(path, "r")
    if file then
      file:close()
      return path
    end
  end
  
  return nil
end

-- 创建启动脚本
-- @param main_script_path 主脚本的完整路径
-- @return boolean 是否成功创建
function AutoStart.create_startup_script(main_script_path)
  local startup_script, startup_dir = get_startup_script_path()
  if not startup_script then
    return false, "无法获取 REAPER 资源路径"
  end
  
  -- 验证主脚本路径是否存在
  local main_file = io.open(main_script_path, "r")
  if not main_file then
    return false, "主脚本文件不存在: " .. tostring(main_script_path)
  end
  main_file:close()
  
  -- 确保启动目录存在
  local create_result = r.RecursiveCreateDirectory(startup_dir, 0)
  if create_result == 0 then
    -- 检查目录是否真的存在（可能创建失败）
    local test_file = io.open(startup_dir .. "/.test", "w")
    if not test_file then
      return false, "无法创建启动脚本目录: " .. tostring(startup_dir)
    end
    test_file:close()
    os.remove(startup_dir .. "/.test")
  end
  
  -- 创建启动脚本内容
  -- 使用绝对路径或相对路径来调用主脚本
  -- 转义路径中的特殊字符
  local escaped_path = main_script_path:gsub("\\", "\\\\"):gsub('"', '\\"')
  local script_content = "-- Auto-start script for zyc_ReaPet\n"
    .. "-- This file is automatically generated. Do not edit manually.\n\n"
    .. "local main_script_path = [[" .. main_script_path .. "]]\n\n"
    .. "-- 检查文件是否存在\n"
    .. "local file = io.open(main_script_path, \"r\")\n"
    .. "if file then\n"
    .. "  file:close()\n"
    .. "  -- 运行主脚本\n"
    .. "  dofile(main_script_path)\n"
    .. "else\n"
    .. "  reaper.ShowMessageBox(\"ReaPet 主脚本未找到:\\n\" .. main_script_path, \"Auto-start Error\", 0)\n"
    .. "end\n"
  
  -- 写入启动脚本
  local file = io.open(startup_script, "w")
  if not file then
    return false, "无法创建启动脚本文件"
  end
  
  file:write(script_content)
  file:close()
  
  return true, "启动脚本已创建"
end

-- 删除启动脚本
-- @return boolean 是否成功删除
function AutoStart.remove_startup_script()
  local startup_script = get_startup_script_path()
  if not startup_script then
    return false, "无法获取 REAPER 资源路径"
  end
  
  -- 检查文件是否存在
  local file = io.open(startup_script, "r")
  if not file then
    -- 文件不存在，认为已经删除成功
    return true, "启动脚本不存在"
  end
  file:close()
  
  -- 删除文件
  local ok, err = os.remove(startup_script)
  if ok then
    return true, "启动脚本已删除"
  else
    return false, "无法删除启动脚本: " .. tostring(err)
  end
end

-- 检查启动脚本是否存在
-- @return boolean 是否存在
function AutoStart.startup_script_exists()
  local startup_script = get_startup_script_path()
  if not startup_script then
    return false
  end
  
  local file = io.open(startup_script, "r")
  if file then
    file:close()
    return true
  end
  
  return false
end

-- 更新启动脚本（根据配置）
-- @param enabled 是否启用自动启动
-- @param main_script_path 主脚本路径（可选，如果不提供则自动查找）
-- @return boolean, string 是否成功，消息
function AutoStart.update_startup_script(enabled, main_script_path)
  if enabled then
    -- 启用自动启动：创建启动脚本
    if not main_script_path then
      main_script_path = get_main_script_path()
    end
    
    if not main_script_path then
      return false, "无法找到主脚本路径"
    end
    
    return AutoStart.create_startup_script(main_script_path)
  else
    -- 禁用自动启动：删除启动脚本
    return AutoStart.remove_startup_script()
  end
end

return AutoStart

